// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:mafia_help/models/best_move.dart';
import 'package:mafia_help/models/club.dart';
import 'package:mafia_help/models/game.dart';
import 'package:mafia_help/models/game_log.dart';
import 'package:mafia_help/models/kill.dart';
import 'package:mafia_help/models/phase.dart';
import 'package:mafia_help/models/player.dart';
import 'package:mafia_help/models/player_ui_model.dart';
import 'package:mafia_help/models/role.dart';
import 'package:mafia_help/models/rule.dart';
import 'package:mafia_help/models/user.dart';
import 'package:mafia_help/models/violation.dart';
import 'package:mafia_help/models/vote.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BestMoveAdapter());
    registerAdapter(ClubAdapter());
    registerAdapter(GameAdapter());
    registerAdapter(GameLogAdapter());
    registerAdapter(KillAdapter());
    registerAdapter(PhaseAdapter());
    registerAdapter(PlayerAdapter());
    registerAdapter(PlayerUIModelAdapter());
    registerAdapter(RoleAdapter());
    registerAdapter(RuleAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(ViolationAdapter());
    registerAdapter(VoteAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BestMoveAdapter());
    registerAdapter(ClubAdapter());
    registerAdapter(GameAdapter());
    registerAdapter(GameLogAdapter());
    registerAdapter(KillAdapter());
    registerAdapter(PhaseAdapter());
    registerAdapter(PlayerAdapter());
    registerAdapter(PlayerUIModelAdapter());
    registerAdapter(RoleAdapter());
    registerAdapter(RuleAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(ViolationAdapter());
    registerAdapter(VoteAdapter());
  }
}
