import 'package:mafia_help/data/local/models/best_move.dart';
import 'package:mafia_help/data/local/models/game.dart';
import 'package:mafia_help/data/local/models/kill.dart';
import 'package:mafia_help/data/local/models/phase.dart';
import 'package:mafia_help/data/local/models/player.dart';
import 'package:mafia_help/data/local/models/vote.dart';
import 'package:mafia_help/domain/helpers/game_end_helper.dart';
import 'package:mafia_help/presentation/state/game_state.dart';

abstract class GameRepository {
  Future<GameState?> loadCurrentGameState();
  Future<void> saveCurrentGameState();
  Future<void> clearCurrentGameState();
  Future<void> saveCompletedGame(GameState finalState);
  Future<List<Game>> getAllCompletedGames();
  Future<Player?> getPlayerBySeat(int seatNumber);
  Future<List<Player>> getAllPlayers();
  Future<List<Player>> getAlivePlayers();
  Future<void> updatePlayerFouls(int seatNumber, int fouls);
  Future<void> setPlayerAlive(int seatNumber, bool isAlive);
  Future<void> updatePlayer(Player player);
  Future<List<int>> getCurrentNominations();
  Future<void> setNominations(List<int> seats);
  Future<Map<int, int>> getCurrentVotes();
  Future<void> addVote({required int round, required int targetSeat, required int voteCount});
  Future<void> clearVotes();
  Future<List<int>> getPartialBestMove();
  Future<void> setPartialBestMove(List<int> digits);
  Future<void> clearPartialBestMove();
  Future<Phase> getCurrentPhase();
  Future<void> setCurrentPhase(Phase phase);
  Future<int> getCurrentSubPhaseIndex();
  Future<void> setCurrentSubPhaseIndex(int index);
  Future<int> getCurrentDay();
  Future<void> setCurrentDay(int day);
  Future<int?> getCurrentSpeaker();
  Future<void> setCurrentSpeaker(int? seatNumber);
  Future<int> getCurrentRound();
  Future<void> setCurrentRound(int round);
  Future<void> setGameEnded(bool ended);
  Future<void> setWinner(GameResult result);
  Future<void> clearAllGameData();
  Future<void> addKill({required int seatNumber, required String phase, required String killType});
  Future<void> addBestMove(List<int> threeSeats);
}